project:
  type: book

book:
  title: "SERVIR's Applied Deep Learning Handbook"
  author:
    - name: Ate Poortinga
      affiliations:
        - id: sig
          name: Spatial Informatics Group, LLC
    - name: Biplov Bhandari
      affiliations:
        - id: woolpert
          name: Woolpert Digital Innovations
    - name: Lilly Thomas
      affiliations:
        - name: Development Seed
    - name: Tim Mayer
      affiliations:
        - id: nasa-servir
          name: NASA - SERVIR
        - id: UofA-huntsville
          name: The University of Alabama in Huntsville

  date: "11/05/2024"
  cover-image: images/Book_Cover.png
  repo-url: https://github.com/tylere/servir-geoai-book/
  repo-actions: [source, edit, issue]
  downloads: [pdf]
  chapters:
    - index.md
    - part: "Curriculum"
      chapters: 
        - 02-Data-Preparation/index.ipynb
        - 03_Semantic_Segmentation/01__Crop_Mapping/notebooks/Rice_Mapping_Bhutan_2021.ipynb
        - 04_Object_Detection/index.ipynb
        - 05_Time_Series/index.ipynb
        - 06_Eco_Process_Sim/index.ipynb
        - 07_Transfer_Learning/index.ipynb
        - 08_Fusion/index.ipynb
        - 09_Downscaling/index.ipynb
        - 10_Future/index.ipynb
        - 11_Ethics/index.ipynb
        - 12_Conclusions/index.ipynb
    - references.qmd
bibliography: references.bib

format:
  html:
    theme:  # pandoc, default, flatly, darkly, sketchy, sandstone, cyborg, zephyr
      light: flatly
      dark: darkly
  pdf:
    documentclass: scrreprt  # book
