project:
  type: book

book:
  title: "SERVIR's Applied Deep Learning Handbook"
  author: "Norah Jones"
  date: "10/31/2024"
  cover-image: images/Book_Cover.png
  chapters:
    - index.md
    - part: "Curriculum"
      chapters: 
        - 02-Data-Preparation/index.ipynb
        - 03_Semantic_Segmentation/01__Crop_Mapping/notebooks/Rice_Mapping_Bhutan_2021.ipynb
        - 04_Object_Detection/index.ipynb
        - 05_Time_Series/index.ipynb
        - 06_Eco_Process_Sim/index.ipynb
        - 07_Transfer_Learning/index.ipynb
        - 08_Fusion/index.ipynb
        - 09_Downscaling/index.ipynb
        - 10_Future/index.ipynb
        - 11_Ethics/index.ipynb
        - 12_Conclusions/index.ipynb
    - references.qmd
bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
